services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  django:
    image: my_django_image
    container_name: django
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
